services:
  - type: web
    name: ai-project-health-backend

    runtime: python

    plan: free

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      alembic upgrade head &&
      uvicorn src.core.main:app --host 0.0.0.0 --port $PORT