"""initial_schema

Revision ID: 1302e115fe2e
Revises: 
Create Date: 2026-07-10 17:26:04.904252
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1302e115fe2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_manager', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ON_HOLD', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('data_confidence_score', sa.Float(), nullable=False),
    sa.Column('total_issues', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('audit_raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_start', sa.DateTime(), nullable=True),
    sa.Column('project_end', sa.DateTime(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('in_progress_tasks', sa.Integer(), nullable=False),
    sa.Column('not_started_tasks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['data_quality_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('planned_start', sa.DateTime(), nullable=True),
    sa.Column('planned_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'IN_PROGRESS', 'NOT_STARTED', name='taskstatus'), nullable=False),
    sa.Column('schedule_health', sa.Enum('GREEN', 'YELLOW', 'RED', name='schedulehealth'), nullable=True),
    sa.Column('audit_raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'IN_PROGRESS', 'NOT_STARTED', name='taskstatus'), nullable=False),
    sa.Column('percent_complete', sa.Float(), nullable=False),
    sa.Column('planned_start', sa.DateTime(), nullable=True),
    sa.Column('planned_end', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('schedule_health', sa.Enum('GREEN', 'YELLOW', 'RED', name='schedulehealth'), nullable=True),
    sa.Column('at_risk', sa.Boolean(), nullable=False),
    sa.Column('on_hold', sa.Boolean(), nullable=False),
    sa.Column('not_applicable', sa.Boolean(), nullable=False),
    sa.Column('predecessors', sa.Text(), nullable=True),
    sa.Column('audit_raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_analysis")
    op.drop_table('tasks')
    op.drop_table('milestones')
    op.drop_table('data_quality_issues')
    op.drop_table('summaries')
    op.drop_table('phases')
    op.drop_table('data_quality_reports')
    op.drop_table('comments')
    op.drop_table('projects')

op.create_table(
    "project_analysis",

    sa.Column(
        "id",
        sa.Integer(),
        primary_key=True,
        autoincrement=True,
    ),

    sa.Column(
        "project_id",
        sa.Integer(),
        sa.ForeignKey("projects.id"),
        nullable=False,
    ),

    sa.Column(
        "rag_status",
        sa.String(20),
        nullable=False,
    ),

    sa.Column(
        "health_score",
        sa.Float(),
        nullable=False,
    ),

    sa.Column(
        "forecast_delay",
        sa.Integer(),
        nullable=False,
    ),

    sa.Column(
        "delay_probability",
        sa.Float(),
        nullable=False,
    ),

    sa.Column(
        "executive_summary",
        sa.Text(),
        nullable=False,
    ),

    sa.Column(
        "recommendations",
        sa.Text(),
        nullable=False,
    ),

    sa.Column(
        "risks",
        sa.Text(),
        nullable=False,
    ),

    sa.Column(
        "created_at",
        sa.DateTime(),
        nullable=False,
    ),
)
    # ### end Alembic commands ###